### ISSUE TITLE
关于“hpm6750evkmini”参考设计原理图

### ISSUE THREAD

**Issue by terenceyhj** [hpmicro/rtt-bsp-hpm6750evkmini#5]
dear: HPM
方便提供“hpm6750evkmini”参考设计原理图？

**Comment by helloeagleyang** [comment]
您好，您可以从https://pan.baidu.com/s/1vJDZWEBqnsosFNeedX6Nww 提取码: cmd5 网盘中 “先楫HPM6750系列资料尝鲜版/PCB Design file”目录下找到您需要的原理图。
